version: '2'
services:
  app:
    build: .
    depends_on:
     - postgres
    environment:
     - "FLASK_APP=maxxbook"
     - "FLASK_DEBUG=True"
     - "LANG=C.UTF-8"
     - "FLASK_DATABASE_URI=postgres://postgres@postgres:5432/maxxbook_dev"
    expose:
     - "3031"
     - "3032"
    links:
     - postgres:postgres
    volumes:
     - ./:/app
  nginx:
    image: nginx:latest
    links:
     - app:uwsgi
    ports:
     - "80:80"
     - "8080:8080"
    volumes:
     - ./nginx/nginx.conf:/etc/nginx/nginx.conf
  postgres:
    image: postgres:latest
    ports:
     - "5432:5432"
